channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-mlflow
      - azureml-sdk
      - azure-ai-ml
      - pyarrow==10.0.0
      - ruamel.yaml==0.17.21
      - scikit-learn==0.24.1
      - pandas==1.2.1
      - joblib==1.0.0
      - matplotlib==3.3.3
